import type { HomeScreenData } from "./home.types";

export const mockHomeScreenData: HomeScreenData = {
  hero: {
    userNameFallback: "Son",
    searchPlaceholder: "Tim khoa hoc: Cyber Security, Big Data...",
    badgeText: "AI powered learning mode",
    headline: "Master the Core",
    highlightedHeadline: "Secure your Future.",
    greeting: "Chao {userName}, AI Assistant da chuan bi lo trinh hoc toi uu cho ban. Bat dau ngay.",
    primaryCta: "get started",
    secondaryCta: "let's explore",
    streakFrames: [
      { value: "7", label: "Ngay hoc lien tiep", detail: "7/10 ngay · Keep going!" },
      { value: "8", label: "Ngay hoc lien tiep", detail: "8/10 ngay · Momentum on" },
      { value: "9", label: "Ngay hoc lien tiep", detail: "9/10 ngay · Almost there" },
    ],
    expFrames: [
      { exp: "12,450", rank: "Top 5% Cyber Defender", delta: "+250" },
      { exp: "12,700", rank: "Top 4% Cyber Defender", delta: "+190" },
      { exp: "12,890", rank: "Top 4% Cyber Defender", delta: "+320" },
    ],
    labFrames: [
      {
        title: "SQL Injection Vulnerability Lab",
        detail: "Thuc hanh phat hien va khai thac lo hong SQL injection",
        status: "Ready to start",
        cta: "Start",
      },
      {
        title: "Network Packet Analyzer Lab",
        detail: "Theo doi packet flow va nhan dien traffic bat thuong",
        status: "Warmup loaded",
        cta: "Launch",
      },
      {
        title: "SOC Incident Response Lab",
        detail: "Xu ly alert, phan tich log va khoanh vung su co",
        status: "Scenario active",
        cta: "Resume",
      },
    ],
    insightFrames: [
      { value: 80, note: "Ban da hoan thanh 80% lo trinh Big Data" },
      { value: 84, note: "Tien do tang len 84%, tiep tuc bai tiep theo" },
      { value: 88, note: "Tien do dat 88%, da san sang cho bai test" },
    ],
    featureCards: [
      { title: "Phu de/Tai lieu chuan", icon: "book" },
      { title: "Lo trinh AI ca nhan hoa", icon: "brain" },
      { title: "Video Full HD voi subtitle", icon: "shield" },
    ],
  },
  catalog: {
    categories: [
      { id: "all", name: "Tat ca" },
      { id: "python", name: "Python" },
      { id: "cybersecurity", name: "Cyber Security" },
      { id: "webdev", name: "Web Dev" },
      { id: "datascience", name: "Data Science" },
      { id: "devops", name: "DevOps" },
      { id: "mobile", name: "Mobile" },
    ],
    courses: [
      {
        id: "1",
        title: "Python cho nguoi moi bat dau - Tu Zero den Hero",
        instructor: "Nguyen Van A",
        thumbnail: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&h=300&fit=crop",
        rating: 4.8,
        reviewCount: 2543,
        duration: "42h 30m",
        students: 15420,
        price: 499000,
        originalPrice: 1299000,
        category: "python",
        level: "Beginner",
      },
      {
        id: "2",
        title: "Ethical Hacking & Penetration Testing Complete Course",
        instructor: "Tran Minh B",
        thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=300&fit=crop",
        rating: 4.9,
        reviewCount: 1876,
        duration: "56h 15m",
        students: 8932,
        price: 799000,
        originalPrice: 1899000,
        category: "cybersecurity",
        level: "Advanced",
      },
      {
        id: "3",
        title: "Full Stack Web Development voi React & Node.js",
        instructor: "Le Thi C",
        thumbnail: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=300&fit=crop",
        rating: 4.7,
        reviewCount: 3421,
        duration: "68h 45m",
        students: 21543,
        price: 699000,
        originalPrice: 1599000,
        category: "webdev",
        level: "Intermediate",
      },
      {
        id: "4",
        title: "Machine Learning & Deep Learning A-Z",
        instructor: "Pham Van D",
        thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=300&fit=crop",
        rating: 4.8,
        reviewCount: 2198,
        duration: "78h 20m",
        students: 12876,
        price: 899000,
        originalPrice: 2199000,
        category: "datascience",
        level: "Advanced",
      },
      {
        id: "5",
        title: "Docker & Kubernetes - DevOps Masterclass",
        instructor: "Hoang Van E",
        thumbnail: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=400&h=300&fit=crop",
        rating: 4.6,
        reviewCount: 1543,
        duration: "35h 10m",
        students: 7654,
        price: 599000,
        originalPrice: 1399000,
        category: "devops",
        level: "Intermediate",
      },
      {
        id: "6",
        title: "React Native - Xay dung ung dung Mobile",
        instructor: "Ngo Thi F",
        thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=300&fit=crop",
        rating: 4.7,
        reviewCount: 1876,
        duration: "48h 30m",
        students: 9876,
        price: 649000,
        originalPrice: 1499000,
        category: "mobile",
        level: "Intermediate",
      },
      {
        id: "7",
        title: "Python Data Analysis voi Pandas & NumPy",
        instructor: "Vu Minh G",
        thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop",
        rating: 4.9,
        reviewCount: 2876,
        duration: "32h 45m",
        students: 18765,
        price: 549000,
        originalPrice: 1199000,
        category: "python",
        level: "Intermediate",
      },
      {
        id: "8",
        title: "Network Security & Firewall Fundamentals",
        instructor: "Dinh Van H",
        thumbnail: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=400&h=300&fit=crop",
        rating: 4.5,
        reviewCount: 987,
        duration: "28h 15m",
        students: 5432,
        price: 449000,
        originalPrice: 999000,
        category: "cybersecurity",
        level: "Beginner",
      },
    ],
    sections: [
      {
        title: "Python & Data Science",
        subtitle: "Nam vung ngon ngu lap trinh pho bien nhat the gioi",
        categoryIds: ["python", "datascience"],
      },
      {
        title: "Cyber Security",
        subtitle: "Bao ve he thong va du lieu khoi cac moi de doa",
        categoryIds: ["cybersecurity"],
      },
      {
        title: "Web & Mobile Development",
        subtitle: "Xay dung ung dung hien dai voi cac cong nghe moi nhat",
        categoryIds: ["webdev", "mobile"],
      },
    ],
  },
};

export async function loadHomeScreenData(): Promise<HomeScreenData> {
  return mockHomeScreenData;
}
