import type { HomeScreenData } from "./home.types";

export const mockHomeScreenData: HomeScreenData = {
  hero: {
    userNameFallback: "Son",
    searchPlaceholder: "Tìm khóa học: Cyber Security, Big Data...",
    badgeText: "AI powered learning mode",
    headline: "Master the Core",
    highlightedHeadline: "Secure your Future.",
    greeting: "Chào {userName}, AI Assistant đã chuẩn bị lộ trình học tối ưu cho bạn. Bắt đầu ngay.",
    primaryCta: "bắt đầu",
    secondaryCta: "khám phá",
    streakFrames: [
      { value: "7", label: "Ngày học liên tiếp", detail: "7/10 ngày • Giữ nhịp học!" },
      { value: "8", label: "Ngày học liên tiếp", detail: "8/10 ngày • Đang vào guồng" },
      { value: "9", label: "Ngày học liên tiếp", detail: "9/10 ngày • Sắp hoàn thành" },
    ],
    expFrames: [
      { exp: "12,450", rank: "Top 5% Backend Developer", delta: "+250" },
      { exp: "12,700", rank: "Top 4% Frontend Developer", delta: "+190" },
      { exp: "12,890", rank: "Top 4% Data Engineer", delta: "+320" },
    ],
    labFrames: [
      {
        title: "SQL Injection Vulnerability Lab",
        detail: "Thực hành phát hiện và khai thác lỗ hổng SQL injection",
        status: "Sẵn sàng bắt đầu",
        cta: "Bắt đầu",
      },
      {
        title: "Network Packet Analyzer Lab",
        detail: "Theo dõi packet flow và nhận diện traffic bất thường",
        status: "Đã thêm tình huống",
        cta: "Mở lab",
      },
      {
        title: "SOC Incident Response Lab",
        detail: "Xử lý alert, phân tích log và khoanh vùng sự cố",
        status:  "đang chạy",
        cta: "Tiếp tục",
      },
    ],
    insightFrames: [
      { value: 80, note: "Bạn đã hoàn thành 80% lộ trình Big Data" },
      { value: 84, note: "Tiến độ tăng lên 84%, tiếp tục bài tiếp theo" },
      { value: 88, note: "Tiến độ đạt 88%, đã sẵn sàng cho bài test" },
    ],
    featureCards: [
      { title: "Phụ đề và tài liệu chuẩn", icon: "book" },
      { title: "Lộ trình AI cá nhân hóa", icon: "brain" },
      { title: "Video Full HD kèm subtitle", icon: "shield" },
    ],
  },
  catalog: {
    categories: [
      { id: "all", name: "Tất cả" },
      { id: "python", name: "Python" },
      { id: "cybersecurity", name: "Cyber Security" },
      { id: "webdev", name: "Web Dev" },
      { id: "datascience", name: "Data Science" },
      { id: "devops", name: "DevOps" },
      { id: "mobile", name: "Mobile" },
    ],
    courses: [
      {
        id: "1",
        title: "Python cho người mới bắt đầu - Từ Zero đến Hero",
        instructor: "Nguyễn Văn A",
        thumbnail: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&h=300&fit=crop",
        rating: 4.8,
        reviewCount: 2543,
        duration: "42h 30m",
        students: 15420,
        price: 499000,
        originalPrice: 1299000,
        category: "python",
        level: "Beginner",
      },
      {
        id: "2",
        title: "Ethical Hacking & Penetration Testing Complete Course",
        instructor: "Trần Minh B",
        thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=300&fit=crop",
        rating: 4.9,
        reviewCount: 1876,
        duration: "56h 15m",
        students: 8932,
        price: 799000,
        originalPrice: 1899000,
        category: "cybersecurity",
        level: "Advanced",
      },
      {
        id: "3",
        title: "Full Stack Web Development với React & Node.js",
        instructor: "Lê Thị C",
        thumbnail: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=300&fit=crop",
        rating: 4.7,
        reviewCount: 3421,
        duration: "68h 45m",
        students: 21543,
        price: 699000,
        originalPrice: 1599000,
        category: "webdev",
        level: "Intermediate",
      },
      {
        id: "4",
        title: "Machine Learning & Deep Learning A-Z",
        instructor: "Phạm Văn D",
        thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=300&fit=crop",
        rating: 4.8,
        reviewCount: 2198,
        duration: "78h 20m",
        students: 12876,
        price: 899000,
        originalPrice: 2199000,
        category: "datascience",
        level: "Advanced",
      },
      {
        id: "5",
        title: "Docker & Kubernetes - DevOps Masterclass",
        instructor: "Hoàng Văn E",
        thumbnail: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=400&h=300&fit=crop",
        rating: 4.6,
        reviewCount: 1543,
        duration: "35h 10m",
        students: 7654,
        price: 599000,
        originalPrice: 1399000,
        category: "devops",
        level: "Intermediate",
      },
      {
        id: "6",
        title: "React Native - Xây dựng ứng dụng Mobile",
        instructor: "Ngô Thị F",
        thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=300&fit=crop",
        rating: 4.7,
        reviewCount: 1876,
        duration: "48h 30m",
        students: 9876,
        price: 649000,
        originalPrice: 1499000,
        category: "mobile",
        level: "Intermediate",
      },
      {
        id: "7",
        title: "Python Data Analysis với Pandas & NumPy",
        instructor: "Vũ Minh G",
        thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop",
        rating: 4.9,
        reviewCount: 2876,
        duration: "32h 45m",
        students: 18765,
        price: 549000,
        originalPrice: 1199000,
        category: "python",
        level: "Intermediate",
      },
      {
        id: "8",
        title: "Network Security & Firewall Fundamentals",
        instructor: "Đinh Văn H",
        thumbnail: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=400&h=300&fit=crop",
        rating: 4.5,
        reviewCount: 987,
        duration: "28h 15m",
        students: 5432,
        price: 449000,
        originalPrice: 999000,
        category: "cybersecurity",
        level: "Beginner",
      },
    ],
    sections: [
      {
        title: "Python & Data Science",
        subtitle: "Nắm vững ngôn ngữ lập trình phổ biến nhất thế giới",
        categoryIds: ["python", "datascience"],
      },
      {
        title: "Cyber Security",
        subtitle: "Bảo vệ hệ thống và dữ liệu khỏi các mối đe dọa",
        categoryIds: ["cybersecurity"],
      },
      {
        title: "Web & Mobile Development",
        subtitle: "Xây dựng ứng dụng hiện đại với các công nghệ mới nhất",
        categoryIds: ["webdev", "mobile"],
      },
    ],
  },
  footerSocials: [
    { label: "Facebook", href: "#" },
    { label: "X", href: "#" },
    { label: "Discord", href: "#" },
  ],
};

export async function loadHomeScreenData(): Promise<HomeScreenData> {
  return mockHomeScreenData;
}
